Video:
    minimum: 1.5Mbps
    recommended: 5Mbps
    priority: 10
VoIP:
    minimum: 100Kbps
    recommended: 300Kbps
    priority: 2
Game:
    minimum: 512Kbps
    recommended: 1Mbps
    priority: 1
    
